### PR TITLE
Python Problems by Shantanu Sharma

### PR DESCRIPTION
**Pull request by Shantanusharma949**

### CODE REVIEW

**Comment by Shantanusharma949** [comment]
Tanya mera commit bhi merge karlo, for Hacktoberfest.

**Comment by tanyagupta0201** [comment]
Okay, I will add but first add author's name and the date modified in your code. For reference, see the codes present in C++ and Java folder.

**Comment by Shantanusharma949** [comment]
Okk

**Comment by Shantanusharma949** [comment]
Now is it fine?

**Pull request closed without merging**
