### PR TITLE
Added banker's algorithm

### PR DESCRIPTION
**Pull request by PRINCECHANDAPILLAI**

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
Writing the author's name and the date modified is a must (Write it as a multiline comment in your code).
For reference, see to the codes present in Java or C++ folder.

**Comment by PRINCECHANDAPILLAI** [comment]
Author PRINCE CHANDAPILLAI
Date 30/10/2001

**Comment by tanyagupta0201** [comment]
> Author PRINCE CHANDAPILLAI Date 30/10/2001

Add this in your file not in comments.

**Comment by tanyagupta0201** [comment]
See to the codes present in C++ or Java folder.

**Comment by tanyagupta0201** [comment]
Also, you don't have to add your DOB 
You need to add the date on which you commited your code.

**Comment by PRINCECHANDAPILLAI** [comment]
Is it ok now

**Pull request merged**
